language: python

install:
  - pip install tox
  - pip install coveralls
  #- pip install python-coveralls

script:
  - tox

after_success:
  - coveralls

# Travis image does not have Python 3.5 yet
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
